### ISSUE TITLE
Default parameters for ranger() optimizer

### ISSUE THREAD

**Issue by Apollo-XI** [fastai/fastai2#20]
First of all, fastai2 is brilliant!!

I found that current default parameters for ranger optimizer are:
```
ranger(p, lr, mom=0.95, wd=0.01, eps=1e-06, sqr_mom=0.99, beta=0.0, decouple_wd=True)
```

However, they are different from lessw2020 repo (https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer). They are:
```
class Ranger(...):
...
     def __init__(self, params, lr=1e-3, alpha=0.5, k=6, N_sma_threshhold=5, betas=(.95,0.999), eps=1e-5, weight_decay=0):
...
```

So, sqr_mon is 0.999 instead of 0.99, eps is 1e-5 and weight_decay=0. Maybe, @lessw2020 point out which are better

**Comment by sgugger** [comment]
Yes we use the same default as our `Adam` for this. Note that we haven't had time to run a lot of experiments yet (we know those are good for Adam) so these are likely to change. Also note that weight decay is always set to a default of `1e-2` by the library (value in `defaults.wd`) so the default wd here has no impact.

Since we keep issues for bug only, I'd suggest moving this discussion to the [forum](https://forums.fast.ai/).
