### ISSUE TITLE
Can't take gradient of TensorBase

### ISSUE THREAD

**Issue by cwza** [fastai/fastai2#278]
Error happens when I try to take the gradient w.r.t. some TensorImage from Dataloaders. 
Here is a simple example:
``` python
inp = TensorBase(torch.tensor(5.)).requires_grad_(True)
# inp = torch.tensor(5.).requires_grad_(True) # This is OK
print(inp)
out = inp**2
grad = torch.autograd.grad(out, inp, only_inputs=True)[0]
print(grad)
```
``` python
TensorBase(5., requires_grad=True)
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn 
```

**Comment by sgugger** [comment]
Yes, you can't pass this at init. This would require PyTorch properly handling subclasses of tensors, but AFAIK, it does not for now (there was a PR with this but I'm not sure it has been merged yet). Our subclasses are not perfect since we can't patch the core of Tensor semantics (and don't really know how) so you should only use the init of `TensorBase` with a tensor.

Also, our semantics are designed to preserve the types for an input pipeline. I have no idea how it plays with autodiff since it was not our primary intention to test it. Closing the issues since we won't do more work on it: this is a patch to address a critically missing piece in PyTorch.

**Comment by cwza** [comment]
But things go wrong even with this stupid example:
``` python
true_img = TensorImage(torch.randn(2, 3, 16, 16)) # get from Dataloaders
# true_img = torch.randn(2, 3, 16, 16) # This is OK
w = torch.tensor(3., requires_grad=True)
fake_img = torch.randn(2, 3, 16, 16) * w # generate from model
def loss_func(fake_img, true_img):
    return ((fake_img-true_img)**2).mean()
loss = loss_func(fake_img, true_img)
loss.backward()
w.grad
```
(fake_img-true_img) automatically becomes TensorImage and pytorch can't deal with it.
I can do something like true_img = true_img.data at somewhere to pass it, but I feel it is not a very good way.

**Comment by sgugger** [comment]
You should cast it back to a plain Tensor when the semantics type get in the way.
Note again that this is a rough patch to let us have semantic types for our input pipelines, and it does not work with all operations so we had to patch in something to preserve the types in our transform.

For as long as PyTorch does not support them natively (which I understand is some goal on their side), I'd just advise to cast back and `Tensor(true_img)` in your loss function. That won't prevent the library to properly decode your result as the dataloader knows to recast things to the types it had (since applying the model often loses the type).

**Comment by cwza** [comment]
The interest thing is Tensor(true_img) will return TensorImage too. I tried detach(), Tensor(), as_tensor() ..., they all return TensorImage. The only thing work is true_img.data.

I think I will write a callback that cast xb, yb to plain tensor before each batch and cast them back after loss to prevent any weird behavior of tensor during computations. 

(Do I need to cast them back after loss? From what you say above, dataloader knows how to handle it while show_batch, show_result?)

Thanks for your reply and hope that pytorch will support tensor subclass better soon.

**Comment by sgugger** [comment]
I tried
```
true_img = TensorImage(torch.randn(2, 3, 16, 16)) # get from Dataloaders
# true_img = torch.randn(2, 3, 16, 16) # This is OK
w = torch.tensor(3., requires_grad=True)
fake_img = torch.randn(2, 3, 16, 16) * w # generate from model
def loss_func(fake_img, true_img):
    return ((fake_img-Tensor(true_img))**2).mean()
loss = loss_func(fake_img, true_img)
loss.backward()
w.grad
```
and it was fine. There may be one thing we can do to help surprises by not patching operations like add and sub. Will try when I have some time.

You won't need to cast them back after loss normally. If you use decode, or show_results, the dataloaders will cast them back.

**Comment by cwza** [comment]
Oh, what I tried is torch.tensor little tensor not torch.Tensor. Oh my god, what's the difference.... The little one give me some warning so I feel not so good and prevent to use it. Seems like "large Tensor" is OK. Cool...

Anyway, I will try callback first. Very thanks!!!
