### ISSUE TITLE
nbdev_test_nbs do not work without a GPU

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastai2#451]
I have opened an issue on nbdev https://github.com/fastai/nbdev/issues/199 about this.  Just posting this cross-referenced issue here for visibility.

**Comment by tmabraham** [comment]
I don't know if this helps, but the following line in `00_torch_core.ipynb` is an example of a test that does not work without GPU available:
```
test_eq_type(t,(3,(tensor(3).cuda(),tensor(2).cuda())))
```
I had this issue too when I was trying to make a change to fastai2 in an environment without GPU. It turned out I didn't need the change in the main fastai2 repository, but I also think nbdev should definitely have some sort of flag for the type of hardware available.

**Comment by jph00** [comment]
Fixed. Use `--flags ''` to skip GPU and slow tests.
